In [1]:
x=2
y=7

In [2]:
x+y

9

In [3]:
x*y

14

In [4]:
%reset -f

In [5]:
x+y

NameError: name 'x' is not defined

In [6]:
%reset -f
x=input("insert nymber")
print(x)

insert nymber6
6


In [18]:
%reset -f
my_list=[3]
for i in list(range(0,4,1)):
    print(i)
    a=int(input())
    print(a)

    #my_list[i]=a

0
6
6
1
5
5
2
4
4
3
2
2


In [22]:
%reset -f
demo_list=[]
demo_list[0]=9
demo_list[1]=5
demo_list[2]=0
demo_list[3]=90
print(demo_list)

IndexError: list assignment index out of range

In [5]:
%reset -f
def inp_from_customer():
    
    input_nums=[]
    for i in list(range(0,5,1)):
        a=int(input("type your number :  \t "))
        input_nums.append(a)
    #print(input_nums)
    return input_nums

def sum_my_list(new_list):
    print("i am here")
    print(new_list[2])

my_returned_list=inp_from_customer()
print(my_returned_list)
sum_my_list(my_returned_list)
    
    

type your number :  	 1
type your number :  	 2
type your number :  	 3
type your number :  	 4
type your number :  	 5
[1, 2, 3, 4, 5]
i am here
3


In [5]:
%reset -f
a=0
print(a,end=" ")
b=1
print(b,end=" ")
for i in range(0,10,1):
    c=a+b
    print(c,end=" ")
    a=b
    b=c


0 1 1 2 3 5 8 13 21 34 55 89 

In [1]:
%reset -f
import numpy as np
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data =np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [2]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [3]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [4]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [5]:
arr = np.zeros((8, 4))

In [6]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
for i in range(8):
    arr[i] = i

In [8]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [10]:
samples = np.random.standard_integers(size=(4, 4))
samples

AttributeError: module 'numpy.random' has no attribute 'standard_integers'

In [11]:
np.random help


SyntaxError: invalid syntax (17950738.py, line 1)

In [13]:
rng = np.random.default_rng(seed=12345)
arr = rng.standard_normal(7) * 5
arr

array([-7.11912518,  6.31864229, -4.35330869, -1.29586617, -0.37671654,
       -3.70442326, -6.83896351])